### ISSUE TITLE
Extremely high canopy temps in BACE exp

### ISSUE THREAD

**Issue by crollinson** [AileneKane/radcliffe#30]
Some of the estimated canopy temperature values in the BACE experiment are extremely high.  There are 87 days with max temperature above 50 C (122 F) and the max is 203 C.  These values occur as early as day 94 (end of March/early April).  Roughly 15 of these occur in the critical March/April time.  The majority happen in late June/July.

I'm re-running the gap filling code and will exclude the 203 C since that's clearly impossible.  I'll leave the others for now, but we should think about what to do about these outliers.

@AileneKane @jsdukes

**Comment by crollinson** [comment]
While we're at it, sherry & marching also have a lot of observations of air temperature > 50 C (305 for sherry, 31 for marching, both warming & unharmed plots).  Here, the weird values start popping in early March (day 66) and 77 occur before day 150 (end of May-ish).

**Comment by crollinson** [comment]
Following up on BACE -- it looks like something got weird with the time stamps for BACE. After running the gap filling on max canopy temp, it looks like some plots have 2 years for what is marked as 1 (see figure below; red dots = my statistical gapfill).  I just went through and double checked to confirm that this problem originates in the expclim.csv file (i.e. before I enter it into my gap filling workflow)

![gapfill_airtemp_max_bace](https://cloud.githubusercontent.com/assets/7927379/15301839/d74a4892-1b7d-11e6-8125-257298b8c6e7.png)

**Comment by jsdukes** [comment]
I don't understand what's going on in the figure.  The doubling of years is strange, but it's also odd that there are 52 plots listed here when BACE should only have 36...

On May 16, 2016, at 3:50 PM, Christy Rollinson wrote:

Following up on BACE -- it looks like something got weird with the time stamps for BACE. After running the gap filling on max canopy temp, it looks like some plots have 2 years for what is marked as 1 (see figure below; red dots = my statistical gapfill). I just went through and double checked to confirm that this problem originates in the expclim.csv file (i.e. before I enter it into my gap filling workflow)

[gapfill_airtemp_max_bace]https://cloud.githubusercontent.com/assets/7927379/15301839/d74a4892-1b7d-11e6-8125-257298b8c6e7.png

**Comment by AileneKane** [comment]
@crollinson I'm finally responding to this, after meeting with @jsdukes via skype today! We looked at the temperatures >50C and it seems that most of them are "real"- that is, they are not the result of a bad sensor or something. Jeff said that these high values occur in plots where there is little vegetation so, rather than being a measure of leaf temperature, they actually reflect soil surface temperatures. I will add something to the metadata file about this. In the meantime, the only canopy temperature measurement that should be thrown out is 203C. For the others, we should leave them in for now, but whether or not they are "valid" depends on how the data are to be used- they are not an accurate measure of leaf temperature, but are an accurate measure of soil surface temperature. let me know if you have questions about this! I'll remove the extreme value and update the expclim.csv file.

**Comment by AileneKane** [comment]
@crollinson I also learned that some of the marchin temperature data needed to be removed. I have done this, and will commit the changes to the updated expclim.csv file. this means the gapfilling will need to be run again! i still haven't heard from sherry yet, so perhaps wait until i hear from her...
