### ISSUE TITLE
Threshold air temperature for soil moisture inclusion

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/radcliffe#44]
@mrjohnston @jsdukes @crollinson If we were to use a threshold air temperature to use to decide whether or not to "count" a particular soil moisture measurement in the summary mean measurement, what would it be (e.g. >0) and why? Please share the reference, or other method you used to come to this number!

**Comment by mrjohnston** [comment]
I think that the measurable, physiologically-relevant water variable most closely (& causally) associated with budburst is sap flow (Urban et al. 2013); soil moisture probably matters a lot when there's sap flow and less before there's sap flow. (There might also be signaling associated with pre-sap flow SM, of course, but it's less clear how that works so it seems more conservative to benchmark with an event we understand better.) If we wanted to accumulate soil moisture starting at the time we expect sap flow to begin, we could do that in a couple of ways:

(1) Determine the temperature at which sap flow typically begins & accumulate soil moisture from this temperature
(2) Determine the typical time between the beginning of sap flow & budburst and accumulate soil moisture over that amount of time

The 'answer' (temperature or time) would differ by species/location, but some literature searching suggests that the time between sap flow and BB is somewhere between 0-14 days:
- Graham et al. 2009 [rhododendron in the San Jacinto mountains of S. CA, see Figure 7]  - ~2 weeks
- Oren and Pataki 2001 [SE deciduous forest, see Fig. 1] - “In the 2 weeks prior to bud break, a low yet detectable flux of water was found in many individuals”
- Urban et al. 2013 [european beech in Czech Republic, see Figure 2] – approx. same time for the beginning of sapflow and budburst
- Lavric et al. 2017 [Quercus pubescens in Slovenia, see Figure 3] – approx. same time for the beginning of sapflow and budburst

...and I didn't find much info re. (1).

That said, another possibility would be to try a number of different SM accumulation times and see which is most predictive in the models. This is my preference, because it feels less arbitrary than a threshold selection and would allow flexibility (the accumulation time might be different at different sites).

[Grahametal2009.pdf](https://github.com/AileneKane/radcliffe/files/3228320/Grahametal2009.pdf)
[OrenandPataki2001.pdf](https://github.com/AileneKane/radcliffe/files/3228322/OrenandPataki2001.pdf)
[Lavricetal2017.pdf](https://github.com/AileneKane/radcliffe/files/3228323/Lavricetal2017.pdf)
[Urbanetal2013.pdf](https://github.com/AileneKane/radcliffe/files/3228317/Urbanetal2013.pdf)

**Comment by AileneKane** [comment]
Closing for now as sap flow will not be relevant for the herbaceous species in our dataset. We may return to this if a reviewer brings something like this up!
