### ISSUE TITLE
update to treats.csv needed and expsiteinfo.csv

### ISSUE THREAD

**Issue by AnneMariePanetta** [AileneKane/radcliffe#9]
dunne site is missing plot 10; temptreat=1

**Comment by AnneMariePanetta** [comment]
temptreat_1 for RMBL data is a little complicated because it was changed toward the beginning of year 3. Reported temptreat_1 is 15W per m^2 from 1991 through May 23, 1993 and 22W per m^2 from May 24, 1993 on (Harte and Shaw 1995).  This has resulted in ~ 1C of warming in 1991-1992, ~1.5C in 1993-1994 (Harte and Shaw 1995, Science).  In the most recent paper from these sites, it is reported that temptreat_1 is 2C (Harte et al 2014, Global Change Biology). (Sorry- this comment is actually more directly related to modifying the expsiteinfo.csv).

**Comment by AileneKane** [comment]
@AnneMariePanetta I updated expsiteinfo.csv so that it says 1 for temptreat_1 for price, and 1.5 for dunnne. does that seem ok? i know it is not perfect, but these are simply the "treatments." annemarie, if you have access to the plot-level data for temperature and we can use it for this meta-analysis that would be fabulous!
